Experiment 1 : Fundamentals of Tensor Operations using PyTorch and NumPy


Create 1D, 2D, and 3D tensors using PyTorch and NumPy.
Show Basic Operations: Element-wise addition, subtraction, multiplication, and division.
Dot product and matrix multiplication.
Indexing and Slicing examples (Boolean masking, extracting subtensors)
Use .view(), .reshape(), .unsqueeze(), and .squeeze() in PyTorch. Compare with .reshape in Numpy
Broadcasting- Perform operations with tensors of different shapes.
In-place vs Out-of-place operations



In [ ]:
import numpy as np

# 1D tensor (vector)
a_np = np.array([1, 2, 3])

# 2D tensor (matrix)
b_np = np.array([[1, 2],
                 [3, 4]])

# 3D tensor
c_np = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a_np.shape)
print(b_np.shape)
print(c_np.shape)


(3,)
(2, 2)
(2, 2, 2)


In [ ]:
import torch

# 1D tensor
a_t = torch.tensor([1, 2, 3])

# 2D tensor
b_t = torch.tensor([[1, 2],
                    [3, 4]])

# 3D tensor
c_t = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a_t.shape)
print(b_t.shape)
print(c_t.shape)


torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2, 2])


In [ ]:
x = torch.tensor([10, 20, 30])
y = torch.tensor([1, 2, 3])

print(x + y)
print(x - y)
print(x * y)
print(x / y)


tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])


In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

dot = torch.dot(a, b)
print(dot)  # 32


tensor(32)


In [ ]:
np.dot(a_np, a_np)


np.int64(14)

In [ ]:
A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

print(torch.matmul(A, B))
# OR
print(A @ B)


tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [ ]:
np.matmul(b_np, b_np)
# OR
b_np @ b_np


array([[ 7, 10],
       [15, 22]])

In [ ]:
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(t[0, 1])
print(t[:, 1])
print(t[1, :])


tensor(20)
tensor([20, 50])
tensor([40, 50, 60])


In [ ]:
x = torch.tensor([1, 2, 3, 4, 5])

mask = x > 3
print(x[mask])  # tensor([4, 5])


tensor([4, 5])


In [ ]:
x_np = np.array([1, 2, 3, 4, 5])
print(x_np[x_np > 3])


[4 5]


In [ ]:
t = torch.arange(1, 13).reshape(3, 4)

sub = t[:2, 1:3]
print(sub)


tensor([[2, 3],
        [6, 7]])


In [ ]:
x = torch.arange(1, 7)

y = x.view(2, 3)
print(y)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
z = x.reshape(3, 2)
print(z)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
x = torch.tensor([1, 2, 3])

print(x.shape)           # [3]
print(x.unsqueeze(0))    # [1, 3]
print(x.unsqueeze(1))    # [3, 1]


torch.Size([3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


In [ ]:
x = torch.tensor([[1, 2, 3]])

print(x.shape)        # [1, 3]
print(x.squeeze())    # [3]


torch.Size([1, 3])
tensor([1, 2, 3])


In [ ]:
np.reshape(a_np, (3, 1))
np.expand_dims(a_np, axis=0)
np.squeeze(np.array([[1, 2, 3]]))


array([1, 2, 3])

In [ ]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

B = torch.tensor([10, 20, 30])

print(A + B)


tensor([[11, 22, 33],
        [14, 25, 36]])


In [ ]:
x = torch.tensor([1, 2, 3])
y = x + 1

print(x)  # unchanged


tensor([1, 2, 3])


In [ ]:
x = torch.tensor([1, 2, 3])
x.add_(1)

print(x)  # modified


tensor([2, 3, 4])
